// Copyright (C) 2019  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details, at
// https://fpgasoftware.intel.com/eula.


// Generated by Quartus Prime Version 19.1 (Build Build 670 09/22/2019)
// Created on Sat Mar 12 16:44:12 2022

OnChipM68xxIO OnChipM68xxIO_inst
(
	.Reset_L(Reset_L_sig) ,	// input  Reset_L_sig
	.Clock_50Mhz(Clock_50Mhz_sig) ,	// input  Clock_50Mhz_sig
	.RS232_RxData(RS232_RxData_sig) ,	// input  RS232_RxData_sig
	.WE_L(WE_L_sig) ,	// input  WE_L_sig
	.DataIn(DataIn_sig) ,	// input [7:0] DataIn_sig
	.GPS_RxData(GPS_RxData_sig) ,	// input  GPS_RxData_sig
	.BlueTooth_RxData(BlueTooth_RxData_sig) ,	// input  BlueTooth_RxData_sig
	.Address(Address_sig) ,	// input [15:0] Address_sig
	.IOSelect_H(IOSelect_H_sig) ,	// input  IOSelect_H_sig
	.ByteSelect_L(ByteSelect_L_sig) ,	// input  ByteSelect_L_sig
	.TouchScreen_RxData(TouchScreen_RxData_sig) ,	// input  TouchScreen_RxData_sig
	.RS232_TxData(RS232_TxData_sig) ,	// output  RS232_TxData_sig
	.ACIA_IRQ(ACIA_IRQ_sig) ,	// output  ACIA_IRQ_sig
	.DataOut(DataOut_sig) ,	// output [7:0] DataOut_sig
	.GPS_TxData(GPS_TxData_sig) ,	// output  GPS_TxData_sig
	.BlueTooth_TxData(BlueTooth_TxData_sig) ,	// output  BlueTooth_TxData_sig
	.TouchScreen_TxData(TouchScreen_TxData_sig) 	// output  TouchScreen_TxData_sig
);

